name: jitsi_meet_platform_interface
description: A common platform interface for the jitsi meet plugin.
version: 2.0.0
homepage: https://github.com/gunschu/jitsi_meet

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
        #ref: master
  jitsi_meet_platform_interface:
    git:
      url: https://github.com/olawhizzy/jitsi_meet_olawhizzy.git
      path: jitsi_meet_platform_interface/
      ref: main
      #ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

